# -*- coding: utf-8 -*-
"""LogisticRegression.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HYWHImiwFLBtkHrHhESLMsXh_wziAhK8
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

data=np.array([[25,30,0],[30,40,1],[20,35,0],[35,45,1]])

y=np.array([0,1,0,1]) # 0=yes will purchase,1-not purchase

xtrain,xtest,ytrain,ytest=train_test_split(data,y,test_size=0.2,random_state=42)

model=LogisticRegression()

model.fit(xtrain,ytrain)
print(model.score(xtest,ytest))

userage=int(input("Enter your age:"))
userduration=int(input("Enter your duration:"))
addtocart=int(input("1 if entered to cart else 0"))
userarray=np.array([[userage,userduration,addtocart]])
ans=model.predict(userarray)
if(ans[0]==1):
  print("Yes user will buy")
else:
  print("No user won't buy")



